
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "emitrades"
  description = "Villager trades for EMI."
  version = "1.0.0"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/pkstDev/EMITrades"
  author = "pkstDev"

# These are global requirements
[requirements]
  minecraft = "~1.19"
  fabricLoader = ">=0.14.9"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    test-mansion = "*"
